language: node_js

os: linux

jobs:
  include:
    - name: 'Automated API tests using Postman CLI'
      arch: amd64
      os: linux
      dist: focal
      node_js:
        - 17
      script:
        # Install Postman CLI
        - curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
        # Login using your Postman API Key
        - postman login --with-api-key $POSTMAN_API_KEY
        # Run your collections using Postman CLI
        - postman collection run "${HOME}/postman/collections/ReqRes.json" -e "6721853-71a85184-d92a-4eb6-8d18-1f21792ac770" --integration-id "132083-${TRAVIS_BUILD_ID}"
        # Lint your API using Postman CLI
        - postman api lint --integration-id 132083
